blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index),
    url(r'^article/(?P<article_id>[0-9]+)$', views.article_page, name="article_page"),
    url(r'^edit/$', views.edit_page, name="edit_page"),
    url(r'^edit/action$', views.edit_action, name="edit_action"),
]

myblog/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Article(models.Model):
    title = models.CharField("标题", max_length=32, default="title")
    category = models.CharField("标签", max_length=20, blank=True)
    create_time = models.DateTimeField("创建时间", auto_now_add=True)
    update_time = models.DateTimeField("修改时间", auto_now=True)
    content = models.TextField("内容", blank=True, null=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render
from blog import models


# Create your views here.

def index(request):
    articles = models.Article.objects.all()
    return render(request, "blog/index.html", {"articles": articles})


def article_page(request, article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request, "blog/article_page.html", {"article": article})


def edit_page(request):
    return render(request, "blog/edit_page.html")


def edit_action(request):
    title = request.POST.get('title', 'TITLE')
    content = request.POST.get('content', 'CONTENT')
    models.Article.objects.create(title=title, content=content)
    articles = models.Article.objects.all()
    return render(request, "blog/index.html", {"articles": articles})

blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>文章页面</title>
</head>
<body>
<h1>{{article.title}}</h1>
<br/>
<h3>{{article.content}}</h3>
<br/><br/>
<a href="">修改文章</a>
</body>
</html>

blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑页面</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token  %}
    <label>文章标题
        <input type="text" name="Title"/>
    </label>
    <br/>
    <label>文章内容
        <input type="text" name="Content"/>
    </label>
    <br/>
    <input type="submit" value="提交">
</form>
</body>
</html>

blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主页</title>
</head>
<body>
<h1>
    <a href="">新文章</a>
</h1>
{% for article in articles %}
<a href="{% url 'blog:article_page' article.id %}">{{article.title}}</a>
<h6>创建时间： {{article.create_time}}</h6>
<br/>
{% endfor %}
</body>
</html>